import type { Metadata } from "next";
import "./globals.css";
import ApolloSetting from "@/commons/settings/apollo-setting";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <ApolloSetting>
          {children}
        </ApolloSetting>
      </body>
    </html>
  );
}